from PyQt5 import QtCore, QtGui, QtWidgets


class PaymentView(QtWidgets.QWidget):
    def __init__(self):
        super(PaymentView, self).__init__()
        self.setupUi()

    def setupUi(self):
        #MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(951, 734)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/50groszy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.setAutoFillBackground(False)
        self.setStyleSheet("background:#ffeead")
        self.TicketsWidget = QtWidgets.QWidget(self)
        self.TicketsWidget.setObjectName("TicketsWidget")
        self.label_title = QtWidgets.QLabel(self.TicketsWidget)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 951, 101))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAutoFillBackground(False)
        self.label_title.setStyleSheet("color: #f6f6f6; background: #3b3a30; border-bottom: 10px solid black")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayoutWidget = QtWidgets.QWidget(self.TicketsWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 180, 341, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_coins = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_coins.setContentsMargins(0, 0, 0, 0)
        self.grid_coins.setObjectName("grid_coins")
        self.button_50_gr = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_50_gr.setMaximumSize(QtCore.QSize(100, 100))
        self.button_50_gr.setAutoFillBackground(False)
        self.button_50_gr.setStyleSheet("background: url(1grosz.jpg)")
        self.button_50_gr.setText("")
        self.button_50_gr.setIcon(icon)
        self.button_50_gr.setIconSize(QtCore.QSize(80, 80))
        self.button_50_gr.setFlat(True)
        self.button_50_gr.setObjectName("button_50_gr")
        self.grid_coins.addWidget(self.button_50_gr, 1, 2, 1, 1)
        self.button_1_gr = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_1_gr.setMaximumSize(QtCore.QSize(100, 100))
        self.button_1_gr.setAutoFillBackground(False)
        self.button_1_gr.setStyleSheet("background: url(1grosz.jpg)")
        self.button_1_gr.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/1grosz.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_1_gr.setIcon(icon1)
        self.button_1_gr.setIconSize(QtCore.QSize(80, 80))
        self.button_1_gr.setFlat(True)
        self.button_1_gr.setObjectName("button_1_gr")
        self.grid_coins.addWidget(self.button_1_gr, 0, 0, 1, 1)
        self.button_2_gr = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_2_gr.setMaximumSize(QtCore.QSize(100, 100))
        self.button_2_gr.setAutoFillBackground(False)
        self.button_2_gr.setStyleSheet("background: url(1grosz.jpg)")
        self.button_2_gr.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/2grosze.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_2_gr.setIcon(icon2)
        self.button_2_gr.setIconSize(QtCore.QSize(80, 80))
        self.button_2_gr.setFlat(True)
        self.button_2_gr.setObjectName("button_2_gr")
        self.grid_coins.addWidget(self.button_2_gr, 0, 1, 1, 1)
        self.button_5_gr = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_5_gr.setMaximumSize(QtCore.QSize(100, 100))
        self.button_5_gr.setAutoFillBackground(False)
        self.button_5_gr.setStyleSheet("background: url(1grosz.jpg)")
        self.button_5_gr.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/5groszy.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_5_gr.setIcon(icon3)
        self.button_5_gr.setIconSize(QtCore.QSize(80, 80))
        self.button_5_gr.setFlat(True)
        self.button_5_gr.setObjectName("button_5_gr")
        self.grid_coins.addWidget(self.button_5_gr, 0, 2, 1, 1)
        self.button_20_gr = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_20_gr.setMaximumSize(QtCore.QSize(100, 100))
        self.button_20_gr.setAutoFillBackground(False)
        self.button_20_gr.setStyleSheet("background: url(1grosz.jpg)")
        self.button_20_gr.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/20groszy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_20_gr.setIcon(icon4)
        self.button_20_gr.setIconSize(QtCore.QSize(80, 80))
        self.button_20_gr.setFlat(True)
        self.button_20_gr.setObjectName("button_20_gr")
        self.grid_coins.addWidget(self.button_20_gr, 1, 1, 1, 1)
        self.button_10_gr = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_10_gr.setMaximumSize(QtCore.QSize(100, 100))
        self.button_10_gr.setAutoFillBackground(False)
        self.button_10_gr.setStyleSheet("background: url(1grosz.jpg)")
        self.button_10_gr.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("assets/10groszy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_10_gr.setIcon(icon5)
        self.button_10_gr.setIconSize(QtCore.QSize(80, 80))
        self.button_10_gr.setFlat(True)
        self.button_10_gr.setObjectName("button_10_gr")
        self.grid_coins.addWidget(self.button_10_gr, 1, 0, 1, 1)
        self.button_1_zl = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_1_zl.setMaximumSize(QtCore.QSize(100, 100))
        self.button_1_zl.setAutoFillBackground(False)
        self.button_1_zl.setStyleSheet("background: url(1grosz.jpg)")
        self.button_1_zl.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("assets/1zloty.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_1_zl.setIcon(icon6)
        self.button_1_zl.setIconSize(QtCore.QSize(80, 80))
        self.button_1_zl.setFlat(True)
        self.button_1_zl.setObjectName("button_1_zl")
        self.grid_coins.addWidget(self.button_1_zl, 2, 0, 1, 1)
        self.button_2_zl = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_2_zl.setMaximumSize(QtCore.QSize(100, 100))
        self.button_2_zl.setAutoFillBackground(False)
        self.button_2_zl.setStyleSheet("background: url(1grosz.jpg)")
        self.button_2_zl.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("assets/2zlote.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_2_zl.setIcon(icon7)
        self.button_2_zl.setIconSize(QtCore.QSize(80, 80))
        self.button_2_zl.setFlat(True)
        self.button_2_zl.setObjectName("button_2_zl")
        self.grid_coins.addWidget(self.button_2_zl, 2, 1, 1, 1)
        self.button_5_zl = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_5_zl.setMaximumSize(QtCore.QSize(100, 100))
        self.button_5_zl.setAutoFillBackground(False)
        self.button_5_zl.setStyleSheet("background: url(1grosz.jpg)")
        self.button_5_zl.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("assets/5zlotych.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_5_zl.setIcon(icon8)
        self.button_5_zl.setIconSize(QtCore.QSize(80, 80))
        self.button_5_zl.setFlat(True)
        self.button_5_zl.setObjectName("button_5_zl")
        self.grid_coins.addWidget(self.button_5_zl, 2, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.TicketsWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(470, 180, 421, 401))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_banknote = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_banknote.setContentsMargins(0, 0, 0, 0)
        self.grid_banknote.setObjectName("grid_banknote")
        self.button_10_zl = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_10_zl.setMaximumSize(QtCore.QSize(200, 100))
        self.button_10_zl.setAutoFillBackground(False)
        self.button_10_zl.setStyleSheet("background: url(1grosz.jpg)")
        self.button_10_zl.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("assets/10zlotych.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_10_zl.setIcon(icon9)
        self.button_10_zl.setIconSize(QtCore.QSize(200, 100))
        self.button_10_zl.setFlat(True)
        self.button_10_zl.setObjectName("button_10_zl")
        self.grid_banknote.addWidget(self.button_10_zl, 0, 0, 1, 1)
        self.button_20_zl = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_20_zl.setMaximumSize(QtCore.QSize(200, 100))
        self.button_20_zl.setAutoFillBackground(False)
        self.button_20_zl.setStyleSheet("background: url(1grosz.jpg)")
        self.button_20_zl.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("assets/20zlotych.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_20_zl.setIcon(icon10)
        self.button_20_zl.setIconSize(QtCore.QSize(200, 100))
        self.button_20_zl.setFlat(True)
        self.button_20_zl.setObjectName("button_20_zl")
        self.grid_banknote.addWidget(self.button_20_zl, 0, 1, 1, 1)
        self.button_50_zl = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_50_zl.setMaximumSize(QtCore.QSize(200, 100))
        self.button_50_zl.setAutoFillBackground(False)
        self.button_50_zl.setStyleSheet("background: url(1grosz.jpg)")
        self.button_50_zl.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("assets/50zlotych.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_50_zl.setIcon(icon11)
        self.button_50_zl.setIconSize(QtCore.QSize(200, 100))
        self.button_50_zl.setFlat(True)
        self.button_50_zl.setObjectName("button_50_zl")
        self.grid_banknote.addWidget(self.button_50_zl, 1, 0, 1, 1)
        self.button_100_zl = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_100_zl.setMaximumSize(QtCore.QSize(200, 100))
        self.button_100_zl.setAutoFillBackground(False)
        self.button_100_zl.setStyleSheet("background: url(1grosz.jpg)")
        self.button_100_zl.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("assets/100zlotych.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_100_zl.setIcon(icon12)
        self.button_100_zl.setIconSize(QtCore.QSize(200, 100))
        self.button_100_zl.setFlat(True)
        self.button_100_zl.setObjectName("button_100_zl")
        self.grid_banknote.addWidget(self.button_100_zl, 1, 1, 1, 1)
        self.button_200_zl = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_200_zl.setMaximumSize(QtCore.QSize(200, 100))
        self.button_200_zl.setAutoFillBackground(False)
        self.button_200_zl.setStyleSheet("background: url(1grosz.jpg)")
        self.button_200_zl.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("assets/200zlotych.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_200_zl.setIcon(icon13)
        self.button_200_zl.setIconSize(QtCore.QSize(200, 100))
        self.button_200_zl.setFlat(True)
        self.button_200_zl.setObjectName("button_200_zl")
        self.grid_banknote.addWidget(self.button_200_zl, 2, 0, 1, 1)
        self.button_500_zl = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_500_zl.setMaximumSize(QtCore.QSize(200, 100))
        self.button_500_zl.setAutoFillBackground(False)
        self.button_500_zl.setStyleSheet("background: url(1grosz.jpg)")
        self.button_500_zl.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("assets/500zlotych.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_500_zl.setIcon(icon14)
        self.button_500_zl.setIconSize(QtCore.QSize(200, 100))
        self.button_500_zl.setFlat(True)
        self.button_500_zl.setObjectName("button_500_zl")
        self.grid_banknote.addWidget(self.button_500_zl, 2, 1, 1, 1)
        self.label_text = QtWidgets.QLabel(self.TicketsWidget)
        self.label_text.setGeometry(QtCore.QRect(10, 110, 931, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_text.setFont(font)
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setObjectName("label_text")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.TicketsWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 640, 891, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontal_payment = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontal_payment.setContentsMargins(0, 0, 0, 0)
        self.horizontal_payment.setSpacing(0)
        self.horizontal_payment.setObjectName("horizontal_payment")
        self.label_payment_left = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_payment_left.setStyleSheet("font-size: 15px; border: 3px solid black; color: #f6f6f6; background: #3b3a30")
        self.label_payment_left.setAlignment(QtCore.Qt.AlignCenter)
        self.label_payment_left.setObjectName("label_payment_left")
        self.horizontal_payment.addWidget(self.label_payment_left)
        self.label_payment_left_value = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_payment_left_value.setStyleSheet("border: 3px solid black; color: #f6f6f6; background: #484f4f; font-size: 15px; ")
        self.label_payment_left_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_payment_left_value.setObjectName("label_payment_left_value")
        self.horizontal_payment.addWidget(self.label_payment_left_value)
        self.label_payment_change = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_payment_change.setStyleSheet("border: 3px solid black; color: #f6f6f6; background: #3b3a30; font-size: 15px; ")
        self.label_payment_change.setAlignment(QtCore.Qt.AlignCenter)
        self.label_payment_change.setObjectName("label_payment_change")
        self.horizontal_payment.addWidget(self.label_payment_change)
        self.label_payment_change_value = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_payment_change_value.setStyleSheet("border: 3px solid black; color: #f6f6f6; background: #484f4f; font-size: 15px; ")
        self.label_payment_change_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_payment_change_value.setObjectName("label_payment_change_value")
        self.horizontal_payment.addWidget(self.label_payment_change_value)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.TicketsWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 540, 231, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontal_ticket_count = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontal_ticket_count.setContentsMargins(0, 0, 0, 0)
        self.horizontal_ticket_count.setSpacing(0)
        self.horizontal_ticket_count.setObjectName("horizontal_ticket_count")
        self.label_ticket_text = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_ticket_text.setStyleSheet("font-size: 15px; border: 3px solid black; color: #f6f6f6; background: #3b3a30")
        self.label_ticket_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ticket_text.setObjectName("label_ticket_text")
        self.horizontal_ticket_count.addWidget(self.label_ticket_text)
        self.label_ticket_count = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_ticket_count.setStyleSheet("border: 3px solid black; color: #f6f6f6; background: #484f4f; font-size: 15px; ")
        self.label_ticket_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ticket_count.setObjectName("label_ticket_count")
        self.horizontal_ticket_count.addWidget(self.label_ticket_count)
        # MainWindow.setCentralWidget(self.TicketsWidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Ticket Machine - PINDOL"))
        self.label_title.setText(_translate("MainWindow", "--- AUTOMAT BILETOWY PINDOL ---"))
        self.label_text.setText(_translate("MainWindow", "Proszę wybrać monety lub banknoty do zapłaty:"))
        self.label_payment_left.setText(_translate("MainWindow", "Pozostało do zapłaty:"))
        self.label_payment_left_value.setText(_translate("MainWindow", "15.00 zł"))
        self.label_payment_change.setText(_translate("MainWindow", "Reszta:"))
        self.label_payment_change_value.setText(_translate("MainWindow", "0.00 zł"))
        self.label_ticket_text.setText(_translate("MainWindow", "Ilość biletów:"))
        self.label_ticket_count.setText(_translate("MainWindow", "4"))
