from PyQt5 import QtCore, QtGui, QtWidgets


class TicketsView(QtWidgets.QMainWindow):
    def __init__(self):
        super(TicketsView, self).__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("TicketsWidget")
        self.resize(950, 732)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.setFont(font)
        self.setAutoFillBackground(False)
        self.TicketsWidget = QtWidgets.QWidget(self)
        self.TicketsWidget.setObjectName("TicketsWidget")
        self.label_title = QtWidgets.QLabel(self.TicketsWidget)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 861, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAutoFillBackground(True)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_tickets_reduced = QtWidgets.QLabel(self.TicketsWidget)
        self.label_tickets_reduced.setGeometry(QtCore.QRect(520, 140, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_tickets_reduced.setFont(font)
        self.label_tickets_reduced.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tickets_reduced.setObjectName("label_tickets_reduced")
        self.gridLayoutWidget = QtWidgets.QWidget(self.TicketsWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 170, 223, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_normal_tickets_first = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_normal_tickets_first.setContentsMargins(0, 0, 0, 0)
        self.grid_normal_tickets_first.setObjectName("grid_normal_tickets_first")
        self.btn_normal_twoway = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_normal_twoway.setObjectName("btn_normal_twoway")
        self.grid_normal_tickets_first.addWidget(self.btn_normal_twoway, 4, 0, 1, 1)
        self.btn_normal_40 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_normal_40.setObjectName("btn_normal_40")
        self.grid_normal_tickets_first.addWidget(self.btn_normal_40, 2, 0, 1, 1)
        self.btn_normal_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_normal_20.setObjectName("btn_normal_20")
        self.grid_normal_tickets_first.addWidget(self.btn_normal_20, 1, 0, 1, 1)
        self.btn_normal_oneway = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_normal_oneway.setObjectName("btn_normal_oneway")
        self.grid_normal_tickets_first.addWidget(self.btn_normal_oneway, 3, 0, 1, 1)
        self.label_tickets_normal = QtWidgets.QLabel(self.TicketsWidget)
        self.label_tickets_normal.setGeometry(QtCore.QRect(80, 130, 221, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_tickets_normal.setFont(font)
        self.label_tickets_normal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tickets_normal.setObjectName("label_tickets_normal")
        self.label_strefa_1 = QtWidgets.QLabel(self.TicketsWidget)
        self.label_strefa_1.setGeometry(QtCore.QRect(20, 170, 21, 201))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_strefa_1.setFont(font)
        self.label_strefa_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_strefa_1.setTextFormat(QtCore.Qt.PlainText)
        self.label_strefa_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_strefa_1.setWordWrap(True)
        self.label_strefa_1.setObjectName("label_strefa_1")
        self.label_strefa_2 = QtWidgets.QLabel(self.TicketsWidget)
        self.label_strefa_2.setGeometry(QtCore.QRect(20, 390, 21, 241))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_strefa_2.setFont(font)
        self.label_strefa_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_strefa_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_strefa_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_strefa_2.setWordWrap(True)
        self.label_strefa_2.setObjectName("label_strefa_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.TicketsWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(520, 170, 223, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_reduced_tickets_first = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_reduced_tickets_first.setContentsMargins(0, 0, 0, 0)
        self.grid_reduced_tickets_first.setObjectName("grid_reduced_tickets_first")
        self.btn_reduced_40 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_reduced_40.setObjectName("btn_reduced_40")
        self.grid_reduced_tickets_first.addWidget(self.btn_reduced_40, 2, 0, 1, 1)
        self.btn_reduced_twoway = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_reduced_twoway.setObjectName("btn_reduced_twoway")
        self.grid_reduced_tickets_first.addWidget(self.btn_reduced_twoway, 4, 0, 1, 1)
        self.btn_reduced_20 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_reduced_20.setObjectName("btn_reduced_20")
        self.grid_reduced_tickets_first.addWidget(self.btn_reduced_20, 1, 0, 1, 1)
        self.btn_reduced_oneway = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_reduced_oneway.setObjectName("btn_reduced_oneway")
        self.grid_reduced_tickets_first.addWidget(self.btn_reduced_oneway, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.TicketsWidget)
        self.line.setGeometry(QtCore.QRect(0, 100, 951, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.TicketsWidget)
        self.line_2.setGeometry(QtCore.QRect(0, 380, 951, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.TicketsWidget)
        self.line_3.setGeometry(QtCore.QRect(0, 640, 951, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.TicketsWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 659, 581, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_total_cost = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_total_cost.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_cost.setObjectName("label_total_cost")
        self.horizontalLayout.addWidget(self.label_total_cost)
        self.label_total_cost_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_total_cost_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_cost_value.setObjectName("label_total_cost_value")
        self.horizontalLayout.addWidget(self.label_total_cost_value)
        self.label_tickets_count = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_tickets_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tickets_count.setObjectName("label_tickets_count")
        self.horizontalLayout.addWidget(self.label_tickets_count)
        self.label_tickets_count_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_tickets_count_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tickets_count_value.setObjectName("label_tickets_count_value")
        self.horizontalLayout.addWidget(self.label_tickets_count_value)
        self.line_4 = QtWidgets.QFrame(self.TicketsWidget)
        self.line_4.setGeometry(QtCore.QRect(263, 650, 20, 101))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.TicketsWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(80, 410, 223, 211))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.grid_normal_tickets_second = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.grid_normal_tickets_second.setContentsMargins(0, 0, 0, 0)
        self.grid_normal_tickets_second.setObjectName("grid_normal_tickets_second")
        self.btn_normal_40_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_normal_40_2.setObjectName("btn_normal_40_2")
        self.grid_normal_tickets_second.addWidget(self.btn_normal_40_2, 2, 0, 1, 1)
        self.btn_normal_twoway_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_normal_twoway_2.setObjectName("btn_normal_twoway_2")
        self.grid_normal_tickets_second.addWidget(self.btn_normal_twoway_2, 4, 0, 1, 1)
        self.btn_normal_20_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_normal_20_2.setObjectName("btn_normal_20_2")
        self.grid_normal_tickets_second.addWidget(self.btn_normal_20_2, 1, 0, 1, 1)
        self.btn_normal_oneway_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_normal_oneway_2.setObjectName("btn_normal_oneway_2")
        self.grid_normal_tickets_second.addWidget(self.btn_normal_oneway_2, 3, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.TicketsWidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(520, 420, 223, 211))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.grid_reduced_tickets_second = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.grid_reduced_tickets_second.setContentsMargins(0, 0, 0, 0)
        self.grid_reduced_tickets_second.setObjectName("grid_reduced_tickets_second")
        self.btn_reduced_40_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_reduced_40_2.setObjectName("btn_reduced_40_2")
        self.grid_reduced_tickets_second.addWidget(self.btn_reduced_40_2, 2, 0, 1, 1)
        self.btn_reduced_twoway_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_reduced_twoway_2.setObjectName("btn_reduced_twoway_2")
        self.grid_reduced_tickets_second.addWidget(self.btn_reduced_twoway_2, 4, 0, 1, 1)
        self.btn_reduced_20_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_reduced_20_2.setObjectName("btn_reduced_20_2")
        self.grid_reduced_tickets_second.addWidget(self.btn_reduced_20_2, 1, 0, 1, 1)
        self.btn_reduced_oneway_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_reduced_oneway_2.setObjectName("btn_reduced_oneway_2")
        self.grid_reduced_tickets_second.addWidget(self.btn_reduced_oneway_2, 3, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.TicketsWidget)
        self.line_5.setGeometry(QtCore.QRect(940, 0, 20, 731))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.payment = QtWidgets.QPushButton(self.TicketsWidget)
        self.payment.setGeometry(QtCore.QRect(610, 660, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.payment.setFont(font)
        self.payment.setObjectName("payment")
        self.line_6 = QtWidgets.QFrame(self.TicketsWidget)
        self.line_6.setGeometry(QtCore.QRect(590, 650, 20, 91))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.TicketsWidget)
        self.line_7.setGeometry(QtCore.QRect(483, 110, 20, 541))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(760, 420, 51, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_reduced_second_minus = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_reduced_second_minus.setContentsMargins(0, 0, 0, 0)
        self.layout_reduced_second_minus.setObjectName("layout_reduced_second_minus")
        self.btn_reduced_20_2_minus = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_20_2_minus.setFont(font)
        self.btn_reduced_20_2_minus.setObjectName("btn_reduced_20_2_minus")
        self.layout_reduced_second_minus.addWidget(self.btn_reduced_20_2_minus)
        self.btn_reduced_40_2_minus = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_40_2_minus.setFont(font)
        self.btn_reduced_40_2_minus.setObjectName("btn_reduced_40_2_minus")
        self.layout_reduced_second_minus.addWidget(self.btn_reduced_40_2_minus)
        self.btn_reduced_oneway_2_minus = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_oneway_2_minus.setFont(font)
        self.btn_reduced_oneway_2_minus.setObjectName("btn_reduced_oneway_2_minus")
        self.layout_reduced_second_minus.addWidget(self.btn_reduced_oneway_2_minus)
        self.btn_reduced_twoway_2_minus = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_twoway_2_minus.setFont(font)
        self.btn_reduced_twoway_2_minus.setObjectName("btn_reduced_twoway_2_minus")
        self.layout_reduced_second_minus.addWidget(self.btn_reduced_twoway_2_minus)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(850, 420, 51, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layout_reduced_second_plus = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_reduced_second_plus.setContentsMargins(0, 0, 0, 0)
        self.layout_reduced_second_plus.setObjectName("layout_reduced_second_plus")
        self.btn_reduced_20_2_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_20_2_plus.setFont(font)
        self.btn_reduced_20_2_plus.setObjectName("btn_reduced_20_2_plus")
        self.layout_reduced_second_plus.addWidget(self.btn_reduced_20_2_plus)
        self.btn_reduced_40_2_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_40_2_plus.setFont(font)
        self.btn_reduced_40_2_plus.setObjectName("btn_reduced_40_2_plus")
        self.layout_reduced_second_plus.addWidget(self.btn_reduced_40_2_plus)
        self.btn_reduced_oneway_2_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_oneway_2_plus.setFont(font)
        self.btn_reduced_oneway_2_plus.setObjectName("btn_reduced_oneway_2_plus")
        self.layout_reduced_second_plus.addWidget(self.btn_reduced_oneway_2_plus)
        self.btn_reduced_twoway_2_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_twoway_2_plus.setFont(font)
        self.btn_reduced_twoway_2_plus.setObjectName("btn_reduced_twoway_2_plus")
        self.layout_reduced_second_plus.addWidget(self.btn_reduced_twoway_2_plus)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(810, 430, 41, 191))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layout_reduced_second_count = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_reduced_second_count.setContentsMargins(0, 0, 0, 0)
        self.layout_reduced_second_count.setObjectName("layout_reduced_second_count")
        self.btn_reduced_20_2_count = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_20_2_count.setFont(font)
        self.btn_reduced_20_2_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_reduced_20_2_count.setObjectName("btn_reduced_20_2_count")
        self.layout_reduced_second_count.addWidget(self.btn_reduced_20_2_count)
        self.btn_reduced_40_2_count = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_40_2_count.setFont(font)
        self.btn_reduced_40_2_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_reduced_40_2_count.setObjectName("btn_reduced_40_2_count")
        self.layout_reduced_second_count.addWidget(self.btn_reduced_40_2_count)
        self.btn_reduced_oneway_2_count = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_oneway_2_count.setFont(font)
        self.btn_reduced_oneway_2_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_reduced_oneway_2_count.setObjectName("btn_reduced_oneway_2_count")
        self.layout_reduced_second_count.addWidget(self.btn_reduced_oneway_2_count)
        self.btn_reduced_twoway_2_count = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_twoway_2_count.setFont(font)
        self.btn_reduced_twoway_2_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_reduced_twoway_2_count.setObjectName("btn_reduced_twoway_2_count")
        self.layout_reduced_second_count.addWidget(self.btn_reduced_twoway_2_count)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(760, 170, 51, 211))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_reduced_20_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_20_minus.setFont(font)
        self.btn_reduced_20_minus.setObjectName("btn_reduced_20_minus")
        self.verticalLayout_7.addWidget(self.btn_reduced_20_minus)
        self.btn_reduced_40_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_40_minus.setFont(font)
        self.btn_reduced_40_minus.setObjectName("btn_reduced_40_minus")
        self.verticalLayout_7.addWidget(self.btn_reduced_40_minus)
        self.btn_reduced_oneway_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_oneway_minus.setFont(font)
        self.btn_reduced_oneway_minus.setObjectName("btn_reduced_oneway_minus")
        self.verticalLayout_7.addWidget(self.btn_reduced_oneway_minus)
        self.btn_reduced_twoway_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_twoway_minus.setFont(font)
        self.btn_reduced_twoway_minus.setObjectName("btn_reduced_twoway_minus")
        self.verticalLayout_7.addWidget(self.btn_reduced_twoway_minus)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(320, 170, 51, 211))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.layout_normal_first_minus = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.layout_normal_first_minus.setContentsMargins(0, 0, 0, 0)
        self.layout_normal_first_minus.setObjectName("layout_normal_first_minus")
        self.btn_normal_20_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_20_minus.setFont(font)
        self.btn_normal_20_minus.setObjectName("btn_normal_20_minus")
        self.layout_normal_first_minus.addWidget(self.btn_normal_20_minus)
        self.btn_normal_40_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_40_minus.setFont(font)
        self.btn_normal_40_minus.setObjectName("btn_normal_40_minus")
        self.layout_normal_first_minus.addWidget(self.btn_normal_40_minus)
        self.btn_normal_oneway_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_oneway_minus.setFont(font)
        self.btn_normal_oneway_minus.setObjectName("btn_normal_oneway_minus")
        self.layout_normal_first_minus.addWidget(self.btn_normal_oneway_minus)
        self.btn_normal_twoway_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_twoway_minus.setFont(font)
        self.btn_normal_twoway_minus.setObjectName("btn_normal_twoway_minus")
        self.layout_normal_first_minus.addWidget(self.btn_normal_twoway_minus)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(320, 410, 51, 211))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.layout_normal_second_minus = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.layout_normal_second_minus.setContentsMargins(0, 0, 0, 0)
        self.layout_normal_second_minus.setObjectName("layout_normal_second_minus")
        self.btn_normal_20_2_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_20_2_minus.setFont(font)
        self.btn_normal_20_2_minus.setObjectName("btn_normal_20_2_minus")
        self.layout_normal_second_minus.addWidget(self.btn_normal_20_2_minus)
        self.btn_normal_40_2_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_40_2_minus.setFont(font)
        self.btn_normal_40_2_minus.setObjectName("btn_normal_40_2_minus")
        self.layout_normal_second_minus.addWidget(self.btn_normal_40_2_minus)
        self.btn_normal_oneway_2_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_oneway_2_minus.setFont(font)
        self.btn_normal_oneway_2_minus.setObjectName("btn_normal_oneway_2_minus")
        self.layout_normal_second_minus.addWidget(self.btn_normal_oneway_2_minus)
        self.btn_normal_twoway_2_minus = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_twoway_2_minus.setFont(font)
        self.btn_normal_twoway_2_minus.setObjectName("btn_normal_twoway_2_minus")
        self.layout_normal_second_minus.addWidget(self.btn_normal_twoway_2_minus)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(370, 180, 41, 191))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.layout_normal_first_count = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.layout_normal_first_count.setContentsMargins(0, 0, 0, 0)
        self.layout_normal_first_count.setObjectName("layout_normal_first_count")
        self.btn_normal_20_count = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_20_count.setFont(font)
        self.btn_normal_20_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_normal_20_count.setObjectName("btn_normal_20_count")
        self.layout_normal_first_count.addWidget(self.btn_normal_20_count)
        self.btn_normal_40_count = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_40_count.setFont(font)
        self.btn_normal_40_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_normal_40_count.setObjectName("btn_normal_40_count")
        self.layout_normal_first_count.addWidget(self.btn_normal_40_count)
        self.btn_normal_oneway_count = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_oneway_count.setFont(font)
        self.btn_normal_oneway_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_normal_oneway_count.setObjectName("btn_normal_oneway_count")
        self.layout_normal_first_count.addWidget(self.btn_normal_oneway_count)
        self.btn_normal_twoway_count = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_twoway_count.setFont(font)
        self.btn_normal_twoway_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_normal_twoway_count.setObjectName("btn_normal_twoway_count")
        self.layout_normal_first_count.addWidget(self.btn_normal_twoway_count)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(370, 420, 41, 191))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.layout_normal_second_count = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.layout_normal_second_count.setContentsMargins(0, 0, 0, 0)
        self.layout_normal_second_count.setObjectName("layout_normal_second_count")
        self.btn_normal_20_2_count = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_20_2_count.setFont(font)
        self.btn_normal_20_2_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_normal_20_2_count.setObjectName("btn_normal_20_2_count")
        self.layout_normal_second_count.addWidget(self.btn_normal_20_2_count)
        self.btn_normal_40_2_count = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_40_2_count.setFont(font)
        self.btn_normal_40_2_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_normal_40_2_count.setObjectName("btn_normal_40_2_count")
        self.layout_normal_second_count.addWidget(self.btn_normal_40_2_count)
        self.btn_normal_oneway_2_count = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_oneway_2_count.setFont(font)
        self.btn_normal_oneway_2_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_normal_oneway_2_count.setObjectName("btn_normal_oneway_2_count")
        self.layout_normal_second_count.addWidget(self.btn_normal_oneway_2_count)
        self.btn_normal_twoway_2_count = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_twoway_2_count.setFont(font)
        self.btn_normal_twoway_2_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_normal_twoway_2_count.setObjectName("btn_normal_twoway_2_count")
        self.layout_normal_second_count.addWidget(self.btn_normal_twoway_2_count)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(410, 170, 51, 211))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.layout_normal_first_plus = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.layout_normal_first_plus.setContentsMargins(0, 0, 0, 0)
        self.layout_normal_first_plus.setObjectName("layout_normal_first_plus")
        self.btn_normal_20_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_20_plus.setFont(font)
        self.btn_normal_20_plus.setObjectName("btn_normal_20_plus")
        self.layout_normal_first_plus.addWidget(self.btn_normal_20_plus)
        self.btn_normal_40_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_40_plus.setFont(font)
        self.btn_normal_40_plus.setObjectName("btn_normal_40_plus")
        self.layout_normal_first_plus.addWidget(self.btn_normal_40_plus)
        self.btn_normal_oneway_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_oneway_plus.setFont(font)
        self.btn_normal_oneway_plus.setObjectName("btn_normal_oneway_plus")
        self.layout_normal_first_plus.addWidget(self.btn_normal_oneway_plus)
        self.btn_normal_twoway_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_twoway_plus.setFont(font)
        self.btn_normal_twoway_plus.setObjectName("btn_normal_twoway_plus")
        self.layout_normal_first_plus.addWidget(self.btn_normal_twoway_plus)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(410, 410, 51, 211))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.layout_normal_second_plus = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.layout_normal_second_plus.setContentsMargins(0, 0, 0, 0)
        self.layout_normal_second_plus.setObjectName("layout_normal_second_plus")
        self.btn_normal_20_2_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_20_2_plus.setFont(font)
        self.btn_normal_20_2_plus.setObjectName("btn_normal_20_2_plus")
        self.layout_normal_second_plus.addWidget(self.btn_normal_20_2_plus)
        self.btn_normal_40_2_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_40_2_plus.setFont(font)
        self.btn_normal_40_2_plus.setObjectName("btn_normal_40_2_plus")
        self.layout_normal_second_plus.addWidget(self.btn_normal_40_2_plus)
        self.btn_normal_oneway_2_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_oneway_2_plus.setFont(font)
        self.btn_normal_oneway_2_plus.setObjectName("btn_normal_oneway_2_plus")
        self.layout_normal_second_plus.addWidget(self.btn_normal_oneway_2_plus)
        self.btn_normal_twoway_2_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_normal_twoway_2_plus.setFont(font)
        self.btn_normal_twoway_2_plus.setObjectName("btn_normal_twoway_2_plus")
        self.layout_normal_second_plus.addWidget(self.btn_normal_twoway_2_plus)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(810, 180, 41, 191))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.layout_reduced_first_count = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.layout_reduced_first_count.setContentsMargins(0, 0, 0, 0)
        self.layout_reduced_first_count.setObjectName("layout_reduced_first_count")
        self.btn_reduced_20_count = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_20_count.setFont(font)
        self.btn_reduced_20_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_reduced_20_count.setObjectName("btn_reduced_20_count")
        self.layout_reduced_first_count.addWidget(self.btn_reduced_20_count)
        self.btn_reduced_40_count = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_40_count.setFont(font)
        self.btn_reduced_40_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_reduced_40_count.setObjectName("btn_reduced_40_count")
        self.layout_reduced_first_count.addWidget(self.btn_reduced_40_count)
        self.btn_reduced_oneway_count = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_oneway_count.setFont(font)
        self.btn_reduced_oneway_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_reduced_oneway_count.setObjectName("btn_reduced_oneway_count")
        self.layout_reduced_first_count.addWidget(self.btn_reduced_oneway_count)
        self.btn_reduced_twoway_count = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_twoway_count.setFont(font)
        self.btn_reduced_twoway_count.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_reduced_twoway_count.setObjectName("btn_reduced_twoway_count")
        self.layout_reduced_first_count.addWidget(self.btn_reduced_twoway_count)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.TicketsWidget)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(850, 170, 51, 211))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.layout_reduced_first_plus = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.layout_reduced_first_plus.setContentsMargins(0, 0, 0, 0)
        self.layout_reduced_first_plus.setObjectName("layout_reduced_first_plus")
        self.btn_reduced_20_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_20_plus.setFont(font)
        self.btn_reduced_20_plus.setObjectName("btn_reduced_20_plus")
        self.layout_reduced_first_plus.addWidget(self.btn_reduced_20_plus)
        self.btn_reduced_40_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_40_plus.setFont(font)
        self.btn_reduced_40_plus.setObjectName("btn_reduced_40_plus")
        self.layout_reduced_first_plus.addWidget(self.btn_reduced_40_plus)
        self.btn_reduced_oneway_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_oneway_plus.setFont(font)
        self.btn_reduced_oneway_plus.setObjectName("btn_reduced_oneway_plus")
        self.layout_reduced_first_plus.addWidget(self.btn_reduced_oneway_plus)
        self.btn_reduced_twoway_plus = QtWidgets.QPushButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reduced_twoway_plus.setFont(font)
        self.btn_reduced_twoway_plus.setObjectName("btn_reduced_twoway_plus")
        self.layout_reduced_first_plus.addWidget(self.btn_reduced_twoway_plus)
        self.setCentralWidget(self.TicketsWidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Ticket Machine - PINDOL"))
        self.label_title.setText(_translate("MainWindow", "--- AUTOMAT BILETOWY PINDOL ---"))
        self.label_tickets_reduced.setText(_translate("MainWindow", "ULGOWE:"))
        self.btn_normal_twoway.setText(_translate("MainWindow", "Dwuprzejazdowy [7.00zł ]"))
        self.btn_normal_40.setText(_translate("MainWindow", "40 minutowy [3.60zł]"))
        self.btn_normal_20.setText(_translate("MainWindow", "20 minutowy [2.00zł]"))
        self.btn_normal_oneway.setText(_translate("MainWindow", "Jednoprzejazdowy [4.00zł]"))
        self.label_tickets_normal.setText(_translate("MainWindow", "NORMALNE:"))
        self.label_strefa_1.setText(_translate("MainWindow", "S T R E F A     I"))
        self.label_strefa_2.setText(_translate("MainWindow", "S T R E F A     I + II"))
        self.btn_reduced_40.setText(_translate("MainWindow", "40 minutowy [1.80zł]"))
        self.btn_reduced_twoway.setText(_translate("MainWindow", "Dwuprzejazdowy [3.50zł ]"))
        self.btn_reduced_20.setText(_translate("MainWindow", "20 minutowy [1.00zł]"))
        self.btn_reduced_oneway.setText(_translate("MainWindow", "Jednoprzejazdowy [2.00zł]"))
        self.label_total_cost.setText(_translate("MainWindow", "Do zapłaty:"))
        self.label_total_cost_value.setText(_translate("MainWindow", "0.00"))
        self.label_tickets_count.setText(_translate("MainWindow", "Ilość biletów:"))
        self.label_tickets_count_value.setText(_translate("MainWindow", "0"))
        self.btn_normal_40_2.setText(_translate("MainWindow", "40 minutowy [4.00zł]"))
        self.btn_normal_twoway_2.setText(_translate("MainWindow", "Dwuprzejazdowy [7.50zł ]"))
        self.btn_normal_20_2.setText(_translate("MainWindow", "20 minutowy [2.50zł]"))
        self.btn_normal_oneway_2.setText(_translate("MainWindow", "Jednoprzejazdowy [4.80zł]"))
        self.btn_reduced_40_2.setText(_translate("MainWindow", "40 minutowy [2.00zł]"))
        self.btn_reduced_twoway_2.setText(_translate("MainWindow", "Dwuprzejazdowy [4.00zł ]"))
        self.btn_reduced_20_2.setText(_translate("MainWindow", "20 minutowy [1.20zł]"))
        self.btn_reduced_oneway_2.setText(_translate("MainWindow", "Jednoprzejazdowy [2.50zł]"))
        self.payment.setText(_translate("MainWindow", "Przejdź do płatności"))
        self.btn_reduced_20_2_minus.setText(_translate("MainWindow", "-"))
        self.btn_reduced_40_2_minus.setText(_translate("MainWindow", "-"))
        self.btn_reduced_oneway_2_minus.setText(_translate("MainWindow", "-"))
        self.btn_reduced_twoway_2_minus.setText(_translate("MainWindow", "-"))
        self.btn_reduced_20_2_plus.setText(_translate("MainWindow", "+"))
        self.btn_reduced_40_2_plus.setText(_translate("MainWindow", "+"))
        self.btn_reduced_oneway_2_plus.setText(_translate("MainWindow", "+"))
        self.btn_reduced_twoway_2_plus.setText(_translate("MainWindow", "+"))
        self.btn_reduced_20_2_count.setText(_translate("MainWindow", "0"))
        self.btn_reduced_40_2_count.setText(_translate("MainWindow", "0"))
        self.btn_reduced_oneway_2_count.setText(_translate("MainWindow", "0"))
        self.btn_reduced_twoway_2_count.setText(_translate("MainWindow", "0"))
        self.btn_reduced_20_minus.setText(_translate("MainWindow", "-"))
        self.btn_reduced_40_minus.setText(_translate("MainWindow", "-"))
        self.btn_reduced_oneway_minus.setText(_translate("MainWindow", "-"))
        self.btn_reduced_twoway_minus.setText(_translate("MainWindow", "-"))
        self.btn_normal_20_minus.setText(_translate("MainWindow", "-"))
        self.btn_normal_40_minus.setText(_translate("MainWindow", "-"))
        self.btn_normal_oneway_minus.setText(_translate("MainWindow", "-"))
        self.btn_normal_twoway_minus.setText(_translate("MainWindow", "-"))
        self.btn_normal_20_2_minus.setText(_translate("MainWindow", "-"))
        self.btn_normal_40_2_minus.setText(_translate("MainWindow", "-"))
        self.btn_normal_oneway_2_minus.setText(_translate("MainWindow", "-"))
        self.btn_normal_twoway_2_minus.setText(_translate("MainWindow", "-"))
        self.btn_normal_20_count.setText(_translate("MainWindow", "0"))
        self.btn_normal_40_count.setText(_translate("MainWindow", "0"))
        self.btn_normal_oneway_count.setText(_translate("MainWindow", "0"))
        self.btn_normal_twoway_count.setText(_translate("MainWindow", "0"))
        self.btn_normal_20_2_count.setText(_translate("MainWindow", "0"))
        self.btn_normal_40_2_count.setText(_translate("MainWindow", "0"))
        self.btn_normal_oneway_2_count.setText(_translate("MainWindow", "0"))
        self.btn_normal_twoway_2_count.setText(_translate("MainWindow", "0"))
        self.btn_normal_20_plus.setText(_translate("MainWindow", "+"))
        self.btn_normal_40_plus.setText(_translate("MainWindow", "+"))
        self.btn_normal_oneway_plus.setText(_translate("MainWindow", "+"))
        self.btn_normal_twoway_plus.setText(_translate("MainWindow", "+"))
        self.btn_normal_20_2_plus.setText(_translate("MainWindow", "+"))
        self.btn_normal_40_2_plus.setText(_translate("MainWindow", "+"))
        self.btn_normal_oneway_2_plus.setText(_translate("MainWindow", "+"))
        self.btn_normal_twoway_2_plus.setText(_translate("MainWindow", "+"))
        self.btn_reduced_20_count.setText(_translate("MainWindow", "0"))
        self.btn_reduced_40_count.setText(_translate("MainWindow", "0"))
        self.btn_reduced_oneway_count.setText(_translate("MainWindow", "0"))
        self.btn_reduced_twoway_count.setText(_translate("MainWindow", "0"))
        self.btn_reduced_20_plus.setText(_translate("MainWindow", "+"))
        self.btn_reduced_40_plus.setText(_translate("MainWindow", "+"))
        self.btn_reduced_oneway_plus.setText(_translate("MainWindow", "+"))
        self.btn_reduced_twoway_plus.setText(_translate("MainWindow", "+"))
        self.show()