from PyQt5 import QtCore, QtGui, QtWidgets


class TicketsView(QtWidgets.QMainWindow):
    def __init__(self):
        super(TicketsView, self).__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("TicketsWidget")
        self.resize(580, 732)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.setFont(font)
        self.setAutoFillBackground(False)
        self.TicketsWidget = QtWidgets.QWidget(self)
        self.TicketsWidget.setObjectName("TicketsWidget")
        self.label_title = QtWidgets.QLabel(self.TicketsWidget)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 571, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAutoFillBackground(True)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_tickets_reduced = QtWidgets.QLabel(self.TicketsWidget)
        self.label_tickets_reduced.setGeometry(QtCore.QRect(320, 140, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_tickets_reduced.setFont(font)
        self.label_tickets_reduced.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tickets_reduced.setObjectName("label_tickets_reduced")
        self.gridLayoutWidget = QtWidgets.QWidget(self.TicketsWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 170, 223, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_normal_tickets_first = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_normal_tickets_first.setContentsMargins(0, 0, 0, 0)
        self.grid_normal_tickets_first.setObjectName("grid_normal_tickets_first")
        self.btn_normal_40 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_normal_40.setObjectName("btn_normal_40")
        self.grid_normal_tickets_first.addWidget(self.btn_normal_40, 2, 0, 1, 1)
        self.btn_normal_twoway = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_normal_twoway.setObjectName("btn_normal_twoway")
        self.grid_normal_tickets_first.addWidget(self.btn_normal_twoway, 4, 0, 1, 1)
        self.btn_normal_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_normal_20.setObjectName("btn_normal_20")
        self.grid_normal_tickets_first.addWidget(self.btn_normal_20, 1, 0, 1, 1)
        self.btn_normal_oneway = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_normal_oneway.setObjectName("btn_normal_oneway")
        self.grid_normal_tickets_first.addWidget(self.btn_normal_oneway, 3, 0, 1, 1)
        self.label_tickets_normal = QtWidgets.QLabel(self.TicketsWidget)
        self.label_tickets_normal.setGeometry(QtCore.QRect(80, 140, 221, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_tickets_normal.setFont(font)
        self.label_tickets_normal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tickets_normal.setObjectName("label_tickets_normal")
        self.label_strefa_1 = QtWidgets.QLabel(self.TicketsWidget)
        self.label_strefa_1.setGeometry(QtCore.QRect(20, 170, 21, 201))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_strefa_1.setFont(font)
        self.label_strefa_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_strefa_1.setTextFormat(QtCore.Qt.PlainText)
        self.label_strefa_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_strefa_1.setWordWrap(True)
        self.label_strefa_1.setObjectName("label_strefa_1")
        self.label_strefa_2 = QtWidgets.QLabel(self.TicketsWidget)
        self.label_strefa_2.setGeometry(QtCore.QRect(20, 390, 21, 241))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_strefa_2.setFont(font)
        self.label_strefa_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_strefa_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_strefa_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_strefa_2.setWordWrap(True)
        self.label_strefa_2.setObjectName("label_strefa_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.TicketsWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(320, 170, 223, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_reduced_tickets_first = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_reduced_tickets_first.setContentsMargins(0, 0, 0, 0)
        self.grid_reduced_tickets_first.setObjectName("grid_reduced_tickets_first")
        self.btn_reduced_40 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_reduced_40.setObjectName("btn_reduced_40")
        self.grid_reduced_tickets_first.addWidget(self.btn_reduced_40, 2, 0, 1, 1)
        self.btn_reduced_twoway = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_reduced_twoway.setObjectName("btn_reduced_twoway")
        self.grid_reduced_tickets_first.addWidget(self.btn_reduced_twoway, 4, 0, 1, 1)
        self.btn_reduced_20 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_reduced_20.setObjectName("btn_reduced_20")
        self.grid_reduced_tickets_first.addWidget(self.btn_reduced_20, 1, 0, 1, 1)
        self.btn_reduced_oneway = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_reduced_oneway.setObjectName("btn_reduced_oneway")
        self.grid_reduced_tickets_first.addWidget(self.btn_reduced_oneway, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.TicketsWidget)
        self.line.setGeometry(QtCore.QRect(0, 100, 591, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.TicketsWidget)
        self.line_2.setGeometry(QtCore.QRect(0, 380, 591, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.TicketsWidget)
        self.line_3.setGeometry(QtCore.QRect(0, 640, 591, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.TicketsWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 659, 581, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_total_cost = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_total_cost.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_cost.setObjectName("label_total_cost")
        self.horizontalLayout.addWidget(self.label_total_cost)
        self.label_total_cost_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_total_cost_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_cost_value.setObjectName("label_total_cost_value")
        self.horizontalLayout.addWidget(self.label_total_cost_value)
        self.label_tickets_count = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_tickets_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tickets_count.setObjectName("label_tickets_count")
        self.horizontalLayout.addWidget(self.label_tickets_count)
        self.label_tickets_count_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_tickets_count_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tickets_count_value.setObjectName("label_tickets_count_value")
        self.horizontalLayout.addWidget(self.label_tickets_count_value)
        self.line_4 = QtWidgets.QFrame(self.TicketsWidget)
        self.line_4.setGeometry(QtCore.QRect(263, 650, 20, 101))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.TicketsWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(80, 410, 223, 211))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.grid_normal_tickets_second = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.grid_normal_tickets_second.setContentsMargins(0, 0, 0, 0)
        self.grid_normal_tickets_second.setObjectName("grid_normal_tickets_second")
        self.btn_normal_40_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_normal_40_2.setObjectName("btn_normal_40_2")
        self.grid_normal_tickets_second.addWidget(self.btn_normal_40_2, 2, 0, 1, 1)
        self.btn_normal_twoway_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_normal_twoway_2.setObjectName("btn_normal_twoway_2")
        self.grid_normal_tickets_second.addWidget(self.btn_normal_twoway_2, 4, 0, 1, 1)
        self.btn_normal_20_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_normal_20_2.setObjectName("btn_normal_20_2")
        self.grid_normal_tickets_second.addWidget(self.btn_normal_20_2, 1, 0, 1, 1)
        self.btn_normal_oneway_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn_normal_oneway_2.setObjectName("btn_normal_oneway_2")
        self.grid_normal_tickets_second.addWidget(self.btn_normal_oneway_2, 3, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.TicketsWidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(320, 410, 223, 211))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.grid_reduced_tickets_second = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.grid_reduced_tickets_second.setContentsMargins(0, 0, 0, 0)
        self.grid_reduced_tickets_second.setObjectName("grid_reduced_tickets_second")
        self.btn_reduced_40_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_reduced_40_2.setObjectName("btn_reduced_40_2")
        self.grid_reduced_tickets_second.addWidget(self.btn_reduced_40_2, 2, 0, 1, 1)
        self.btn_reduced_twoway_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_reduced_twoway_2.setObjectName("btn_reduced_twoway_2")
        self.grid_reduced_tickets_second.addWidget(self.btn_reduced_twoway_2, 4, 0, 1, 1)
        self.btn_reduced_20_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_reduced_20_2.setObjectName("btn_reduced_20_2")
        self.grid_reduced_tickets_second.addWidget(self.btn_reduced_20_2, 1, 0, 1, 1)
        self.btn_reduced_oneway_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn_reduced_oneway_2.setObjectName("btn_reduced_oneway_2")
        self.grid_reduced_tickets_second.addWidget(self.btn_reduced_oneway_2, 3, 0, 1, 1)
        self.setCentralWidget(self.TicketsWidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Ticket Machine - PINDOL"))
        self.label_title.setText(_translate("MainWindow", "--- AUTOMAT BILETOWY PINDOL ---"))
        self.label_tickets_reduced.setText(_translate("MainWindow", "ULGOWE:"))
        self.btn_normal_40.setText(_translate("MainWindow", "40 minutowy [3.60zł]"))
        self.btn_normal_twoway.setText(_translate("MainWindow", "Dwuprzejazdowy [7.00zł ]"))
        self.btn_normal_20.setText(_translate("MainWindow", "20 minutowy [2.00zł]"))
        self.btn_normal_oneway.setText(_translate("MainWindow", "Jednoprzejazdowy [4.00zł]"))
        self.label_tickets_normal.setText(_translate("MainWindow", "NORMALNE:"))
        self.label_strefa_1.setText(_translate("MainWindow", "S T R E F A     I"))
        self.label_strefa_2.setText(_translate("MainWindow", "S T R E F A     I + II"))
        self.btn_reduced_40.setText(_translate("MainWindow", "40 minutowy [1.80zł]"))
        self.btn_reduced_twoway.setText(_translate("MainWindow", "Dwuprzejazdowy [3.50zł ]"))
        self.btn_reduced_20.setText(_translate("MainWindow", "20 minutowy [1.00zł]"))
        self.btn_reduced_oneway.setText(_translate("MainWindow", "Jednoprzejazdowy [2.00zł]"))
        self.label_total_cost.setText(_translate("MainWindow", "Do zapłaty:"))
        self.label_total_cost_value.setText(_translate("MainWindow", "0.00"))
        self.label_tickets_count.setText(_translate("MainWindow", "Ilość biletów:"))
        self.label_tickets_count_value.setText(_translate("MainWindow", "0"))
        self.btn_normal_40_2.setText(_translate("MainWindow", "40 minutowy [4.00zł]"))
        self.btn_normal_twoway_2.setText(_translate("MainWindow", "Dwuprzejazdowy [7.50zł ]"))
        self.btn_normal_20_2.setText(_translate("MainWindow", "20 minutowy [2.50zł]"))
        self.btn_normal_oneway_2.setText(_translate("MainWindow", "Jednoprzejazdowy [4.80zł]"))
        self.btn_reduced_40_2.setText(_translate("MainWindow", "40 minutowy [2.00zł]"))
        self.btn_reduced_twoway_2.setText(_translate("MainWindow", "Dwuprzejazdowy [4.00zł ]"))
        self.btn_reduced_20_2.setText(_translate("MainWindow", "20 minutowy [1.20zł]"))
        self.btn_reduced_oneway_2.setText(_translate("MainWindow", "Jednoprzejazdowy [2.50zł]"))
        self.show()